---
# tasks file for autoelk
- name: launching ELK-MASTER01 instance
  ec2:
    key_name: xxx 
    instance_type: t2.micro
    image: xxxxxxxxx
    group: SSMSecurityGroupForLinuxInstances
    vpc_subnet_id: xxxxx
    region: us-east-1
    instance_tags:
     Name: ELK-MASTER01
- name: launching ELK-MASTER02 instance
  ec2:
    key_name: xxxxx
    instance_type: t2.micro
    image: xxxxxx
    group: xxxxxxxxxxx
    vpc_subnet_id: xxxxxxxxx
    region: us-east-1
    instance_tags:
     Name: ELK-MASTER02

- name: creating app security group
  ec2_group:
    name: "{{ app_name }}"
    description: "{{ app_name }} security group"
    region: "{{ region }}"
    rules: "{{ sec_group_rules }}"
    vpc_id: "{{ vpc_id }}"
  tags: security_groups
  register: app_security_group


- name: launching load balancer
  ec2_elb_lb:
    name: "{{ app_name }}"
    region: "{{ region }}"
    state: present
    subnets: "{{ subnets | join(',') }}"
    security_group_ids: "{{ app_security_group.group_id }}"
    connection_draining_timeout: 60
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/" 
        response_timeout: 5 
        interval: 30 
        unhealthy_threshold: 5
        healthy_threshold: 5
  tags: load_balancer

- name: creating launch config
  ec2_lc:
    name: "{{ app_name }}"
    image_id: "{{ ami }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    security_groups: "{{ app_security_group.group_id }}"
    instance_type: "{{ instance_size }}"
  tags: launch_config

- name: creating autoscale group
  ec2_asg:
    name: "{{ app_name }}"
    load_balancers: "{{ app_name }}"
    launch_config_name: "{{ app_name }}"
    min_size: "{{ min_size }}"
    max_size: "{{ max_size }}"
    termination_policies: "{{ termination_policies }}"
    default_cooldown: 60
    desired_capacity: "{{ desired_capacity }}"
    region: "{{ region }}"
    vpc_zone_identifier: "{{ subnets | join(',') }}"
    health_check_type: EC2
    health_check_period: 60


- name: creating scale down  policy
  ec2_scaling_policy:
    state: present
    region: "{{ region }}"
    name: autoscale-down-policy
    adjustment_type: ChangeInCapacity
    asg_name: "{{ app_name }}"
    scaling_adjustment: -1
    min_adjustment_step: -1
    cooldown: 60
  register: scale_down_policy
  tags: scaling_policy

- name: creating scale up policy
  ec2_scaling_policy:
    state: present
    region: "{{ region }}"
    name: autoscale-up-policy
    adjustment_type: ChangeInCapacity
    asg_name: "{{ app_name }}"
    scaling_adjustment: 1
    min_adjustment_step: 1
    cooldown: 60
  register: scale_up_policy
  tags: scaling_policy

- name: creating scale down alarm
  ec2_metric_alarm:
    state: present
    region: "{{ region }}"
    name: "cpu-utilization-low"
    metric: CPUUtilization
    namespace: "AWS/EC2"
    statistic: Average
    comparison: "<"
    threshold: 40.0
    period: 60
    evaluation_periods: 1
    unit: "Percent"
    description: "This will alarm when cpu usage average is lower than 40% for 1 minute "
    dimensions: 
      AutoScalingGroupName: "{{ app_name }}"
    alarm_actions: 
    - "{{ scale_down_policy.arn }}"
  tags: alarm

- name: creating scale up alarm
  ec2_metric_alarm:
    state: present
    region: "{{ region }}"
    name: "cpu-utilization-high"
    metric: CPUUtilization
    namespace: "AWS/EC2"
    statistic: Average
    comparison: ">="
    threshold: 60.0
    period: 60
    evaluation_periods: 1
    unit: "Percent"
    description: "This will alarm when cpu usage average is higher than 60% for 1 minute "
    dimensions: 
      AutoScalingGroupName: "{{ app_name }}"
    alarm_actions: 
      - "{{ scale_up_policy.arn }}"
  tags: alarm
